---
title: "Commodity Futures Forward Curves"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE , warning = FALSE, message = FALSE)

library(flexdashboard)
library(shiny)
library(ggplot2)
library(quantmod)
library(xts)
library(lubridate)
#library(ArgumentCheck)
library(ustyc) 
library(officer)
library(ggiraph)

```

```{r functions, echo=FALSE, warning = FALSE, message = FALSE}
# Import helper functions for building tickers

source("functions.R")

```

```{r introcompute, echo=FALSE}
# Performs initial logic to build 8 nearest ticker symbols for display later

Today <- Sys.Date()
mo <- as.integer(month(Today))
Year <- as.numeric(year(Today))

MonthCode <- month_symbol(mo)
Cm <- get_nearby_corn(MonthCode, Year)
Sm <- get_nearby_soy(MonthCode, Year)

corn_contract6 <- corn_forward6(Cm[[1]], Cm[[2]])
corn_contract6 <- cbind(corn_contract6, "", "","","", "")
wheat_contract6 <- corn_forward6(Cm[[1]], Cm[[2]])
wheat_contract6 <- cbind(wheat_contract6, "", "","","", "")

soy_contract8 <- soy_forward8(Sm[[1]], Sm[[2]])
soy_contract8 <- cbind(soy_contract8, "", "","","", "")

crude_contract12 <- crude_forward12(MonthCode, Year)
crude_contract12 <- cbind(crude_contract12, "", "","","", "")
codes <- c('F', 'G', 'H', 'J', 'K', 'M', 'N', 'Q', 'U', 'V', 'X', 'Z')

# Fetch Corn Quotes
for (i in 1:6){
 
  corn_contract6[i, 3] <- paste0("C", corn_contract6[i,1], substr(corn_contract6[i, 2], 3,4), ".", "CBT")
  corn_contract6[i, 4] <- as.numeric(getQuote(corn_contract6[i,3])[2])
  corn_contract6[i, 5] <- format(as.Date(paste0(sprintf("%02d", match(corn_contract6[i,1], codes)), "/", "14", "/", substr(corn_contract6[i, 2], 3,4)), "%m/%d/%y"), "%Y-%m-%d")
  corn_contract6[i, 6] <- as.Date(corn_contract6[i, 5]) - Sys.Date()
}

# Fetch Wheat Quotes
for (i in 1:6){
  
  wheat_contract6[i, 3] <- paste0("W", wheat_contract6[i,1], substr(wheat_contract6[i, 2], 3,4), ".", "CBT")
  wheat_contract6[i, 4] <- as.numeric(getQuote(wheat_contract6[i,3])[2])
  wheat_contract6[i, 5] <- format(as.Date(paste0(sprintf("%02d", match(wheat_contract6[i,1], codes)), "/", "14", "/", substr(wheat_contract6[i, 2], 3,4)), "%m/%d/%y"), "%Y-%m-%d")
  wheat_contract6[i, 6] <- as.Date(wheat_contract6[i, 5]) - Sys.Date()
}

# Fetch Soy Quotes
for (i in 1:8){
  
  soy_contract8[i, 3] <- paste0("S", soy_contract8[i,1], substr(soy_contract8[i, 2], 3,4), ".", "CBT")
  soy_contract8[i, 4] <- as.numeric(getQuote(soy_contract8[i,3])[2])
  soy_contract8[i, 5] <- format(as.Date(paste0(sprintf("%02d", match(soy_contract8[i,1], codes)), "/", "14", "/", substr(soy_contract8[i, 2], 3,4)), "%m/%d/%y"), "%Y-%m-%d")
  soy_contract8[i, 6] <- as.Date(soy_contract8[i, 5]) - Sys.Date()
} 

# Fetch Crude Quotes
for (i in 1:12){
 
  crude_contract12[i, 3] <- paste0("CL", crude_contract12[i,1], substr(crude_contract12[i, 2], 3,4), ".", "NYM")
  crude_contract12[i, 4] <- as.numeric(getQuote(crude_contract12[i,3])[2])
  crude_contract12[i, 5] <- format(as.Date(paste0(sprintf("%02d", match(crude_contract12[i,1], codes)), "/", "14", "/", substr(crude_contract12[i, 2], 3,4)), "%m/%d/%y"), "%Y-%m-%d")
  crude_contract12[i, 6] <- as.Date(crude_contract12[i, 5]) - Sys.Date()
}
```


```{r plotprep, echo=FALSE}
# Prep for plotting
colnames(corn_contract6) <- c("Month", "Year", "Contract", "Price", "Expiration", "DTE", "Label")
colnames(wheat_contract6) <- c("Month", "Year", "Contract", "Price", "Expiration", "DTE", "Label")
colnames(soy_contract8) <- c("Month", "Year", "Contract", "Price", "Expiration", "DTE", "Label")
colnames(crude_contract12) <- c("Month", "Year", "Contract", "Price", "Expiration", "DTE", "Label")

corn_contract6 <- as.data.frame(corn_contract6)
corn_contract6$Contract <- substr(corn_contract6$Contract, 1,4)
corn_contract6$DTE <- as.numeric(as.character(corn_contract6$DTE))
corn_contract6$Price <- as.numeric(as.character(corn_contract6$Price))
corn_contract6$Label <- paste(corn_contract6$Contract, corn_contract6$Price)
C_DRet30 <- as.numeric(as.character(round(diff( corn_contract6$Price)/diff(corn_contract6$DTE)*30, digits = 2)))
c_label2 <- paste(corn_contract6$Contract[-8], C_DRet30)

wheat_contract6 <- as.data.frame(wheat_contract6)
wheat_contract6$Contract <- substr(wheat_contract6$Contract, 1,4)
wheat_contract6$DTE <- as.numeric(as.character(wheat_contract6$DTE))
wheat_contract6$Price <- as.numeric(as.character(wheat_contract6$Price))
wheat_contract6$Label <- paste(wheat_contract6$Contract, wheat_contract6$Price)
w_DRet30 <- round(diff( wheat_contract6$Price)/diff(wheat_contract6$DTE)*30, digits = 2)
w_label2 <- paste(wheat_contract6$Contract[-8], w_DRet30)

soy_contract8 <- as.data.frame(soy_contract8)
soy_contract8$Contract <- substr(soy_contract8$Contract, 1,4)
soy_contract8$DTE <- as.numeric(as.character(soy_contract8$DTE))
soy_contract8$Price <- as.numeric(as.character(soy_contract8$Price))
soy_contract8$Label <- paste(soy_contract8$Contract, soy_contract8$Price)
s_DRet30 <- round(diff( soy_contract8$Price)/diff(soy_contract8$DTE)*30, digits = 2)
s_label2 <- paste(soy_contract8$Contract[-8], s_DRet30)

crude_contract12 <- as.data.frame(crude_contract12)
crude_contract12$Contract <- substr(crude_contract12$Contract, 1,5)
crude_contract12$DTE <- as.numeric(as.character(crude_contract12$DTE))
crude_contract12$Price <- as.numeric(as.character(crude_contract12$Price))
crude_contract12$Label <- paste(crude_contract12$Contract, crude_contract12$Price)
Crude_DRet30 <- as.numeric(as.character(round(diff( crude_contract12$Price)/diff(crude_contract12$DTE)*30, digits = 2)))
crude_label2 <- paste(crude_contract12$Contract[-8], Crude_DRet30)
```



```{r ggplots, echo=FALSE}
# Define the ggplots
c <- ggplot(corn_contract6, aes(DTE, Price, color = Price)) + 
      xlim(c(0, 450)) +
      geom_line(size = .75) +
      expand_limits(y=c(min(corn_contract6$Price)-50, max(corn_contract6$Price)+50)) +
      geom_point_interactive(aes(tooltip = Label), size = 2) +
      theme_bw(base_size = 14) +  theme(plot.title = element_text(hjust = 0.5), legend.position="none") + 
      labs(x = "Days to Expiration", y = "Price of Corn in Cents per Bushel", title = "Corn Forward Curve")

w <- ggplot(wheat_contract6, aes(DTE, Price, color = Price)) + 
      xlim(c(0, 450)) +
      geom_line(size = .75) +
      expand_limits(y=c(min(wheat_contract6$Price)-50, max(wheat_contract6$Price)+50)) +
      geom_point_interactive(aes(tooltip = Label), size = 2) +
      theme_bw(base_size = 14) +  theme(plot.title = element_text(hjust = 0.5), legend.position="none") + 
      labs(x = "Days to Expiration", y = "Price of wheat in Cents per Bushel", title = "Chicago Wheat Forward Curve")

s <- ggplot(soy_contract8, aes(DTE, Price, color = Price)) + 
      xlim(c(0, 450)) +
      geom_line(size = .75) +
      expand_limits(y=c(min(soy_contract8$Price)-50, max(soy_contract8$Price)+50)) +
      geom_point_interactive(aes(tooltip = Label), size = 2) +
      theme_bw(base_size = 12) +  theme(plot.title = element_text(hjust = 0.5), legend.position="none") + 
      labs(x = "Days to Expiration", y = "Price of Soybean in Cents per Bushel", title = "Soybean Forward Curve")

cl <- ggplot(crude_contract12, aes(DTE, Price, color = Price)) + 
      xlim(c(0, 450)) +
      geom_line(size = .75) +
      expand_limits(y=c(min(crude_contract12$Price)-5, max(crude_contract12$Price)+5)) +
      geom_point_interactive(aes(tooltip = Label), size = 2) +
      theme_bw(base_size = 12) +  theme(plot.title = element_text(hjust = 0.5), legend.position="none") + 
      labs(x = "Days to Expiration", y = "Price of Crude Oil in Dollars per Barrel", title = "WTI Crude Oil Forward Curve")

```



Column {data-width=200}
-----------------------------------------------------------------------

### Introduction

Corn, soybeans, and wheat are [Chicago Board of Trade](http://www.cmegroup.com/company/cbot.html) futures contracts; crude oil is a [New York Mercantile Exchange](http://www.cmegroup.com/company/nymex.html) futures contract. Price quotes are pulled from [Yahoo Finance](https://finance.yahoo.com/). Hover your mouse over the lines to reveal the contracts plotted. 


Column {.tabset}
-----------------------------------------------------------------------


### Corn

```{r, echo = FALSE}
ggiraphOutput("cornplot")
output$cornplot <- renderggiraph({
    ggiraph(code = print(c), pointsize = 14, flexdashboard = TRUE)
  })
```


### Soybeans

```{r, echo = FALSE}
ggiraphOutput("soybeanplot")

output$soybeanplot <- renderggiraph({
    ggiraph(code = print(s), s, pointsize = 14, flexdashboard = TRUE)
  })
```


### Wheat 


```{r, echo = FALSE}
ggiraphOutput("wheatplot")

output$wheatplot <-    renderggiraph({
    ggiraph(code = print(w), pointsize = 14, flexdashboard = TRUE)
  })
```

### WTI Crude Oil 


```{r, echo = FALSE}
ggiraphOutput("crudeplot")

output$crudeplot <-    renderggiraph({
    ggiraph(code = print(cl), pointsize = 14, flexdashboard = TRUE)
  })
```

### Bitcoin

[CME Bitcoin Futures](http://www.cmegroup.com/trading/bitcoin-futures.html)

Coming soon! Check back after December 10, 2017.
